django_blog/django_blog/urls.py
from django.contrib import admin

# 记得引入include
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    # 新增代码，配置app的url
    path('', include('articles.urls', namespace='articles')),
    path('', include('users.urls', namespace='users')),
    path('password-reset/', include('password_reset.urls')),
]

django_blog/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
]

django_blog/users/models.py
from django.db import models
from django.contrib.auth.models import User
# 引入内置信号
from django.db.models.signals import post_save

# 引入信号接收器的装饰器
from django.dispatch import receiver
# Create your models here.


# 用户扩展信息
class Profile(models.Model):
    # 与 User 模型构成一对一的关系
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    # 电话号码字段
    phone = models.CharField(max_length=20, blank=True)
    # 头像
    avatar = models.ImageField(upload_to='avatar/%Y%m%d/', blank=True)
    # 个人简介
    bio = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return 'user {}'.format(self.user.username)


# 信号接收函数，每当新建 User 实例时自动调用
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


# 信号接收函数，每当更新 User 实例时自动调用
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

django_blog/users/views.py
import logging
import json

from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from .users_form import UserLoginForm, UserRegisterForm
# 引入验证登录的装饰器
from django.contrib.auth.decorators import login_required


# Create your views here.
logger=logging.getLogger(__name__)


@login_required(login_url='/user/login/')
def user_delete(request, id):
    user = User.objects.get(id=id)
    # 验证登录用户、待删除用户是否相同
    if request.user == user:
        #退出登录，删除数据并返回博客列表
        logout(request)
        user.delete()
        return redirect("articles:articles_list")
    else:
        return HttpResponse("你没有删除操作的权限。")

def user_register(request):
    if request.method == 'POST':
        logger.debug('准备提交表单')
        user_register_form = UserRegisterForm(data=request.POST)
        # logger.debug(request.POST)
        # logger.debug(user_register_form)
        # logger.debug(user_register_form.username)
        # logger.debug(user_register_form.repeat_password)
        # logger.debug(user_register_form.password)

        if user_register_form.is_valid():
            logger.debug('验证通过')
            new_user = user_register_form.save(commit=False)
            # 设置密码
            new_user.set_password(user_register_form.cleaned_data['password'])
            new_user.save()
            # 保存好数据后立即登录并返回博客列表页面
            login(request, new_user)
            return redirect("articles:articles_list")
        else:
            #取出验证失败的信息,方便定位问题,给用用户提示
            ErrorDict=user_register_form.errors

            Error_Str=json.dumps(ErrorDict)


            Error_Dict=json.loads(Error_Str)

            # for value in  Error_Dict.values():
            #     logger.debug(value)
            # return HttpResponse(ErrorDict.__repr__())
            return HttpResponse(Error_Dict.values())
    elif request.method == 'GET':
        logger.debug('开始注册')
        user_register_form = UserRegisterForm()
        context = { 'form': user_register_form }
        return render(request, 'users/register.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")


# 用户退出
def user_logout(request):
    data = request.POST
    logger.debug('用户：%r退出成功'%data)

    logout(request)

    return redirect("articles:articles_list")


#用户登录
def user_login(request):
    if request.method == 'POST':
        user_login_form = UserLoginForm(data=request.POST)
        data=request.POST

        logger.debug('用户：%r正在登录' %data)
        logger.debug('用户：%r正在登录' %data.get('username') )

        if user_login_form.is_valid():
            # .cleaned_data 清洗出合法数据
            data = user_login_form.cleaned_data
            # 检验账号、密码是否正确匹配数据库中的某个用户
            # 如果均匹配则返回这个 user 对象
            user = authenticate(username=data['username'], password=data['password'])

            if user:
                # 将用户数据保存在 session 中，即实现了登录动作
                login(request, user)

                logger.debug('用户：%r登录成功' % (user.username))

                return redirect("articles:articles_list")
            else:
                return HttpResponse("账号或密码输入有误。请重新输入~")
        else:
            return HttpResponse("账号或密码输入不合法")
    elif request.method == 'GET':
        user_login_form = UserLoginForm()
        context = { 'form': user_login_form }
        return render(request, 'users/login.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")

django_blog/templates/users/login.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 登录 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">

            <form method="post" action=".">
                {% csrf_token %}
                <!-- 账号 -->
                <div class="form-group">
                    <label for="username">账号</label>
                    <input type="text" class="form-control" id="username" name="username">
                </div>
                <!-- 密码 -->
                <div class="form-group">
                    <label for="password">密码</label>
                    <input type="password" class="form-control" id="password" name="password">
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
            <br>
                <h5>还没有账号？</h5>
                <h5>点击<a href='{% url "users:register" %}'>注册账号</a>加入我们吧！</h5>
                <!-- 新增 -->
                <h5>忘记密码了？</h5>
                <h5>点击<a href='{% url "password_reset_recover" %}'>这里</a>重置密码</h5>
            <br>

        </div>


    </div>
</div>
{% endblock content %}

django_blog/templates/users/register.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 登录 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="POST" action=".">
                {% csrf_token %}
{#                  {% for field in form %}#}
{#                    <div class="fieldWrapper">#}
{#                        {{ field.errors }}#}
{#                        {{ field.label_tag }} {{ field }}#}
{#                    </div>#}
{#                  {% endfor %}#}
                <!-- 账号 -->
                <div class="form-group col-md-4">
                    <label for="username">昵称</label>
                    <input type="text" class="form-control" id="username" name="username" required>
                </div>
                <!-- 邮箱 -->
                <div class="form-group col-md-4">
                    <label for="email">Email</label>
                    <input type="text" class="form-control" id="email" name="email">
                </div>
                <!-- 密码 -->
                <div class="form-group col-md-4">
                    <label for="password">设置密码</label>
                    <input type="password" class="form-control" id="password" name="password" required>
                </div>
                <!-- 确认密码 -->
                <div class="form-group col-md-4">
                    <label for="repeat_password">确认密码</label>
                    <input type="password" class="form-control" id="repeat_password" name="repeat_password" required>
                </div>

                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}