django_blog/articles/urls.py
from django.urls import path

# 正在部署的应用的名称
app_name = 'articles'

from . import views
# from articles import views
urlpatterns = [
    #博客主页
    path('', views.articles_list, name='home'),
    #文章列表
    path('articles', views.articles_list, name='articles_list'),
    #文章详情
    path('article_detail/<int:id>/', views.article_detail, name='article_detail'),
    #创建文章
    path('article_create/', views.article_create, name='article_create'),
    #删除文章
    path('article_delete/<int:id>/', views.article_delete, name='article_delete'),
    #修改文章
    path('article_update/<int:id>/', views.article_update, name='article_update'),

]

django_blog/django_blog/urls.py
from django.contrib import admin

# 记得引入include
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    # 新增代码，配置app的url
    path('', include('articles.urls', namespace='articles')),
    path('', include('users.urls', namespace='users')),
    path('password-reset/', include('password_reset.urls')),
]

django_blog/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
]

django_blog/articles/models.py
# Create your models here.
from django.db import models

# 导入内建的User模型。
from django.contrib.auth.models import User
# timezone 用于处理时间相关事务。
from django.utils import timezone



# 博客文章数据模型
class ArticlesPost(models.Model):


    # 文章作者。参数 on_delete 用于指定数据删除的方式
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    # 文章标题。models.CharField 为字符串字段，用于保存较短的字符串，比如标题
    title = models.CharField(max_length=100)

    # 文章正文。保存大量文本使用 TextField
    body = models.TextField()

    # 文章创建时间。参数 default=timezone.now 指定其在创建数据时将默认写入当前的时间
    created = models.DateTimeField(default=timezone.now)

    # 文章更新时间。参数 auto_now=True 指定每次数据更新时自动写入当前时间
    updated = models.DateTimeField(auto_now=True)

    # 内部类 class Meta 用于给 model 定义元数据
    class Meta:
        # ordering 指定模型返回的数据的排列顺序
        # '-created' 表明数据应该以倒序排列
        ordering = ('-created',)

    # 函数 __str__ 定义当调用对象的 str() 方法时的返回值内容
    def __str__(self):
        # return self.title 将文章标题返回
        return self.title

django_blog/articles/forms.py
# 引入表单类
from django import forms
# 引入文章模型
from .models import ArticlesPost

# 写文章的表单类
class ArticlesPostForm(forms.ModelForm):
    class Meta:
        # 指明数据模型来源
        model = ArticlesPost
        # 定义表单包含的字段
        fields = ('title', 'body')

django_blog/articles/views.py
# Create your views here.
# 导入 HttpResponse 模块
import logging

import markdown

# 导入数据模型ArticlePost
from .models import ArticlesPost

# 引入redirect重定向模块
from django.shortcuts import render, redirect
# 引入HttpResponse
from django.http import HttpResponse
# 引入刚才定义的ArticlePostForm表单类
from .forms import ArticlesPostForm
# 引入User模型
from django.contrib.auth.models import User

from utils.set_log import setup_logger

#设置日志
setup_logger(log_file='server.log')
logger=logging.getLogger(__name__)


#修改文章
# 更新文章
def article_update(request, id):
    """
    更新文章的视图函数
    通过POST方法提交表单，更新titile、body字段
    GET方法进入初始表单页面
    id： 文章的 id
    """

    # 获取需要修改的具体文章对象
    article = ArticlesPost.objects.get(id=id)
    # 判断用户是否为 POST 提交表单数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        article_post_form = ArticlesPostForm(data=request.POST)
        logger.debug('更新文章的内容：%r'%request.POST)

        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            # 保存新写入的 title、body 数据并保存
            article.title = request.POST['title']
            article.body = request.POST['body']
            article.save()
            # 完成后返回到修改后的文章中。需传入文章的 id 值
            return redirect("articles:article_detail", id=id)
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")

    # 如果用户 GET 请求获取数据
    else:
        # 创建表单类实例
        # article_post_form = ArticlesPostForm()
        # 赋值上下文，将 article 文章对象也传递进去，以便提取旧的内容
        # context = { 'article': article, 'article_post_form': article_post_form }
        context = { 'article': article}
        # 将响应返回到模板中
        return render(request, 'articles/update.html', context)




# 删文章
def article_delete(request, id):
    # 根据 id 获取需要删除的文章
    article = ArticlesPost.objects.get(id=id)


    #获取文章标题
    article_title=article.title

    # 调用.delete()方法删除文章
    article.delete()
    # 完成删除后返回文章列表
    logger.debug('删除文章%r成功'%article_title)
    return redirect("articles:articles_list")

# 写文章的视图
def article_create(request):
    # 判断用户是否提交数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        article_post_form = ArticlesPostForm(data=request.POST)
        logger.debug(type(article_post_form))

        logger.debug(request.user.username)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            # 保存数据，但暂时不提交到数据库中
            new_article = article_post_form.save(commit=False)
            logging.debug(type(new_article))

            # 指定数据库中 id=1 的用户为作者
            # 如果你进行过删除数据表的操作，可能会找不到id=1的用户
            # 此时请重新创建用户，并传入此用户的id
            # new_article.author = User.objects.get(id=10)
            #获取当前登录用户名
            username=request.user.username
            new_article.author = User.objects.get(username=username)
            logging.debug(new_article.author)
            # 将新文章保存到数据库中
            new_article.save()
            # 完成后返回到文章列表
            return redirect("articles:articles_list")
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")

    # 如果用户请求获取数据
    else:
        logging.debug(request.content_params)
        logging.debug(request.body)
        logging.debug(request)

        # 创建表单类实例
        article_post_form = ArticlesPostForm()
        # 赋值上下文
        context = { 'article_post_form': article_post_form }
        # 返回模板
        return render(request, 'articles/create.html', context)


def article_detail(request, id):
    # 取出相应的文章
    article = ArticlesPost.objects.get(id=id)
    # 将markdown语法渲染成html样式
    article.body = markdown.markdown(article.body,
                                     extensions=[
                                         # 包含 缩写、表格等常用扩展
                                         'markdown.extensions.extra',
                                         # 语法高亮扩展
                                         'markdown.extensions.codehilite',
                                     ])

    # 需要传递给模板的对象
    context = { 'article_content': article }
    # 载入模板，并返回context对象
    return render(request, 'articles/detail.html', context)


# 视图函数
def articles_list(request):
    # 取出所有博客文章
    articles = ArticlesPost.objects.all()
    # 需要传递给模板（templates）的对象
    context = { 'articles': articles }
    # render函数：载入模板，并返回context对象
    return render(request, 'articles/article_list.html', context)
def index(request):

    return HttpResponse("Hello my blog!")

# def articles_list(request):
#
#
#     return HttpResponse("Hello World!")

django_blog/templates/articles/article_list.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    首页
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->
<div class="container">
    <div class="row mt-2">

        {% for article in articles %}
        <!-- 文章内容 -->
        <div class="col-4 mb-4">
        <!-- 卡片容器 -->
            <div class="card h-100">
                <!-- 标题 -->
                <h4 class="card-header">{{ article.title|slice:'20' }}</h4>
                <!-- 摘要 -->
                <div class="card-body">
                    <p class="card-text">{{ article.body|slice:'100' }}...</p>
                </div>
                <!-- 注脚 -->
                <div class="card-footer">
                    <a href="#" class="btn btn-primary">阅读本文</a>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
</div>
{% endblock content %}

django_blog/templates/articles/artlist_back.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>文章列表</title>
</head>
<body>
{% for article in articles %}
    <p>{{ article.title }}</p>
{% endfor %}
</body>
</html>

django_blog/templates/articles/create.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %} {% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %} 写文章 {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表单 -->
            <form method="post" action=".">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="title">文章标题</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

django_blog/templates/articles/detail.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    王金玉文章详情
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 文章详情 -->
<div class="container">
    <div class="row">
        <!-- 标题及作者 -->
        <h1 class="col-12 mt-4 mb-4">{{ article_content.title }}</h1>
        <div class="col-12 alert alert-success">作者：{{ article_content.author | safe }}</div>
        · <a href="#" onclick="confirm_delete()">删除文章</a>
        · <a href="{% url "articles:article_update" article_content.id %}">编辑文章</a>
{#        · <a href="{% url "articles:article_delete" article_content.id %}">删除文章</a>#}

        <!-- 文章正文 -->
        <div class="col-12">
            <p>{{ article_content.body |safe }}</p>
        </div>
    </div>
</div>

 <script>
    // 删除文章的函数
    function confirm_delete() {
        // 调用layer弹窗组件
        layer.open({
            // 弹窗标题
            title: "确认删除",
            // 正文
            content: "确认删除这篇文章吗？",
            // 点击确定按钮后调用的回调函数
            yes: function(index, layero) {
                // 指定应当前往的 url
                location.href='{% url "articles:article_delete" article_content.id %}'
            },
        })
    }
</script>

{% endblock content %}

django_blog/templates/articles/update.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 修改文章 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <!-- 在 value 属性中指定文本框的初始值为旧的内容，即 article 对象中的 title 字段 -->
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}