django_blog/articles/urls.py
from django.urls import path

# 正在部署的应用的名称
app_name = 'articles'

from . import views
# from articles import views
urlpatterns = [
    #博客主页
    path('', views.articles_list, name='home'),
    #文章列表
    path('articles', views.articles_list, name='articles_list'),
    #文章详情
    path('article_detail/<int:id>/', views.article_detail, name='article_detail'),
    #创建文章
    path('article_create/', views.article_create, name='article_create'),
    #删除文章
    path('article_delete/<int:id>/', views.article_delete, name='article_delete'),
    #修改文章
    path('article_update/<int:id>/', views.article_update, name='article_update'),

]

django_blog/django_blog/urls.py
from django.contrib import admin

# 记得引入include
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    # 新增代码，配置app的url
    path('', include('articles.urls', namespace='articles')),
    path('', include('users.urls', namespace='users')),
    path('password-reset/', include('password_reset.urls')),
]

django_blog/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
]

django_blog/templates/base.html
<!-- 载入静态文件 -->
{% load staticfiles %}

<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- 引入monikai.css -->
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
</head>

<body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}
    <!-- 预留具体页面的位置 -->
    {% block content %}{% endblock content %}
    <!-- 引入注脚 -->
    {% include 'footer.html' %}
    <!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
    <script src="{% static 'jquery/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'popper/popper.js' %}"></script>
    <!-- 引入bootstrap的js文件 -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'layer/layer.js' %}"></script>
</body>

</html>

django_blog/templates/footer.html
{% load staticfiles %}
<!-- Footer -->
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; www.dusaiphoto.com 2018</p>
    </div>
</footer>

django_blog/templates/header.html
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">

    <!-- 导航栏商标 -->
    <a class="navbar-brand" href="#">王金玉的博客</a>

    <!-- 导航入口 -->
    <div>
      <ul class="navbar-nav">
        <!-- 条目 -->
        <li class="nav-item">
          <a class="nav-link" href="#">文章</a>
        </li>
        <li class="nav-item"><a class="nav-link"
            href="{% url 'articles:article_create' %}">写文章</a>
        </li>
          <!-- Django的 if 模板语句 -->
        {% if user.is_authenticated %}
            <!-- 如果用户已经登录，则显示用户名下拉框 -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ user.username }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>
                  <a class="dropdown-item" href="{% url "users:user_logout" %}">退出登录</a>
                </div>
            </li>
        <!-- 如果用户未登录，则显示 “登录” -->
        {% else %}
            <li class="nav-item">
                                           {# user_login对应 name='user_login'#}
                <a class="nav-link" href="{% url 'users:user_login' %}">登录</a>
            </li>
        <!-- if 语句在这里结束 -->
        {% endif %}
      </ul>
    {% if user.is_authenticated %}
            <script>
                function user_delete() {
                    // 调用layer弹窗组件
                    layer.open({
                        title: "确认删除",
                        content: "确认删除用户资料吗？",
                        yes: function(index, layero) {
                            location.href='{% url "users:delete" user.id %}'
                        },
                    })
                }
            </script>
    {% endif %}

    </div>

  </div>
</nav>